version: "3.9"

services:
  vugopress:
    build: .
    container_name: vugopress
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vugopress
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: "postgres:17"
    container_name: vugopress_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: vugopress
    volumes:
      - ./vugopress-db-data:/var/lib/postgresql/data
    ports:
        - "5438:5432"
volumes:
  vugopress-db-data:
